
# name
name: Compile Java Backend

# on
on: [push, pull_request]

# jobs
jobs:
  compile-backend:
    runs-on: ubuntu-latest
    name: Compile Backend Code
    steps:
      - uses: actions/checkout@v3
# name
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

# cache
      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

# name
      - name: Compile with Maven
        run: |
          cd app
          ./mvnw clean compile
  
